IMDB <- read.csv("IMDBMovieData.csv", header = TRUE)
class(IMDB)
names(IMDB)
dim(IMDB)
str(IMDB)
summary(IMDB)
IMDB <- IMDB[!is.na(MD$gross),] 
library("ggplot2")
library("GGally")
summary(IMDB)
summary(Filter(is.numeric, IMDB))
IMDB <- IMDB[!is.na(IMDB$gross) | is.na(IMDB$director_facebook_likes), ]
summary(IMDB$gross)
summary(IMDB$director_facebook_likes)
IMDB <- IMDB[!is.na(IMDB$director_facebook_likes),]
summary(IMDB$director_facebook_likes)
MiddleScores <- subset(IMDB, IMDB$imdb_score >= 5.5 & IMDB$imdb_score < 7.5)           
summary(Filter(is.numeric, MiddleScores))              
HighScores <- subset(IMDB, IMDB$imdb_score >= 7.5)
LowScores <- subset(IMDB, IMDB$imdb_score < 5.5)
summary(HighScores)
summary(LowScores)
plot(HighScores$imdb_score, HighScores$actor_1_facebook_likes, xlab= "IMDB Score", ylab= "Actor 1 Facebook Likes", main= "High IMDB Scores by Actor 1 Facebook Likes", col= "blue")
plot(LowScores$imdb_score, LowScores$actor_1_facebook_likes, xlab= "IMDB Score", ylab ="Actor 1 Facebook Likes", main="Low IMDB Scores by Actore 1 Facebook Likes", col= "blue")
par(xpd=TRUE)
data("iris")
str(IMDB$director_name)
summary(IMDB$director_name)
plot(IMDB$imdb_score ~ IMDB$actor_1_facebook_likes, ylab = "IMDB Score", xlab= "Number of Actor One FaceBook Likes", col= ifelse(IMDB$imdb_score >=5.5,"Yellow", "Black"))
boxplot(IMDB$imdb_score~ IMDB$actor_1_facebook_likes)
boxplot(IMDB$imdb_score ~IMDB$gross)
